Removed NLP Event
aravindvnair99/AYKYA-Fest pull request #116
Opened 2020-11-04 12:57 UTC by suneel87

Signed-off-by: Suneel Nadipalli <nsuneel89@gmail.com>

2020-11-05 06:12 UTC, aravindvnair99 requested changes
@suneel87 Why remove VLSI?

2020-11-06 07:26 UTC, suneel87 commented
> @suneel87 Why remove VLSI?

@aravindvnair99 Coz nextTech is the exact same file....why have two? vlsi.ejs isn't even routed

2020-11-06 07:27 UTC, aravindvnair99 commented
> > @suneel87 Why remove VLSI?
> 
> @aravindvnair99 Coz nextTech is the exact same file....why have two? vlsi.ejs isn't even routed

Alright, I'll merge it then.

2020-11-06 07:27 UTC, aravindvnair99 approved these changes

2020-11-06 07:27 UTC, merged