Created the second version of members page
aravindvnair99/AYKYA-Fest pull request #27
Opened 2020-09-21 17:18 UTC by suneel87

Signed-off-by: Suneel Nadipalli <nsuneel89@gmail.com>

Fixes #
-Incorporated new template into members page(from speaker 2 page)
-Replaced template images and names with final images and names
-Images(70px by 70px) appear above name on hovering over dev team at the end of every page(footer)
-Image has white-border, and different image for each team member(using template images for now)
-Introduced spaces after comma and letter-spacing to make more space for images

2020-09-22 13:18 UTC, VinayakTekade submitted a review, later dismissed

2020-09-22 17:32 UTC, aravindvnair99 requested changes
A few things to be noted:

- When using dark mode, always make sure the contrast of text in foreground matches that of the dark background.
- Don't update template files. Those are just temporary files and would cause unnecessary time spent in reviewing those changes.
- Web browsers do not require large resolution images. Such images only make sense when trying to print where the DPI and other things matters. That isn't so for normal web browsing. So, resize and compress accordingly. 4K images aren't required for the web. SD or HD would be more than sufficient. When replacing images, make sure to check the resolution and replace with an image of the same resolution which avoids unnecessary file sizes, large images and also alignment issues.
- Let's keep things organised to avoid any future confusions or unnecessary relocation. So make sure to place all things within correct folders with appropriate file names.
- Use the Chrome Dev Tools or any such tool to check the view for various screen resolutions.
- GitHub and Firebase servers are Linux servers where the file names and extensions are case sensitive. So don't mix and match such as `jpg` and `JPG` for example. Let's stick to a standard to avoid 404s and use `jpg` for all `jpg` / `jpeg` images.

A few things to work on as per above (tick them once done and re-request a review):

- [ ] Alignment of `/members` in mobile view does not seem right
- [ ] Compress images
- [ ] Resize images
- [ ] Use correct file names and folders
- [ ] Instead of plain names, add a link to their LinkedIn profiles. I've put it for me as an example. Follow the same.

@suneel87 Moving this to draft until all issues are fixed. Mark as `Ready for review` once done.

@PriyaaIyer @Subaharish You both can also take note to avoid the same issue again in your respective branches. Recheck on your branches as well.

@VinayakTekade Recheck these before approving next time.

2020-09-25 06:50 UTC, VinayakTekade submitted a review, later dismissed

2020-09-25 16:03 UTC, aravindvnair99 approved these changes

2020-09-25 16:03 UTC, merged