Added jumbotron in upcoming page
aravindvnair99/AYKYA-Fest pull request #29
Opened 2020-09-25 05:53 UTC by Subaharish

Signed-off-by: Subaharish <48942935+Subaharish@users.noreply.github.com>

2020-09-25 13:26 UTC, VinayakTekade requested changes
The padding and margin of each card are too much for mobile screens. Check the screen responsiveness of the page.

2020-09-25 13:31 UTC, Subaharish commented
> The padding and margin of each card are too much for mobile screens. Check the screen responsiveness of the page.

2020-09-25 13:32 UTC, Subaharish commented
> > The padding and margin of each card are too much for mobile screens. Check the screen responsiveness of the page.

@VinayakTekade  this is just for desktop as of now. We'll do that also

2020-09-27 04:28 UTC, VinayakTekade submitted a review, later dismissed

2020-10-05 07:31 UTC, VinayakTekade submitted a review, later dismissed

2020-10-11 16:06 UTC, aravindvnair99 approved these changes

2020-10-11 16:07 UTC, merged