Made some minor changes to event Gallery Page
aravindvnair99/AYKYA-Fest pull request #36
Opened 2020-09-28 13:02 UTC by suneel87

Signed-off-by: Suneel Nadipalli <nsuneel89@gmail.com>

Fixes #
-Removed the other template events (only 3 have been left in)
-Replaced template images of remaining 3 events with images(compressed) from college
-Removed "Load More" button at the bottom

## Proposed Changes
-
-
-

2020-09-28 13:08 UTC, suneel87 commented
@aravindvnair99 @VinayakTekade I've made the requested changes in the Event Gallery Page

2020-09-30 16:55 UTC, Subaharish commented
@suneel87 Pictures are not added in the individual blog pages.

2020-10-01 08:36 UTC, suneel87 commented
@Subaharish @aravindvnair99 @VinayakTekade I have added the pictures for the individual blog pages

2020-10-05 07:30 UTC, VinayakTekade approved these changes

2020-10-10 09:19 UTC, aravindvnair99 commented on functions/views/eventGallery.ejs
> +					<!--&lt;!&ndash; blog-item-4 &ndash;&gt;
```suggestion
					<!--
```

2020-10-10 09:19 UTC, aravindvnair99 commented on functions/views/eventGallery.ejs
> +					&lt;!&ndash; blog-item-5 &ndash;&gt;
```suggestion
```

2020-10-10 09:20 UTC, aravindvnair99 commented on functions/views/eventGallery.ejs
> +					&lt;!&ndash; blog-item-6 &ndash;&gt;
```suggestion
```

2020-10-10 09:20 UTC, aravindvnair99 commented on functions/views/eventGallery.ejs
> +					&lt;!&ndash; blog-item-7  &ndash;&gt;
```suggestion
```

2020-10-10 09:20 UTC, aravindvnair99 commented on functions/views/eventGallery.ejs
> +					&lt;!&ndash; blog-item-8 &ndash;&gt;
```suggestion
```

2020-10-10 09:22 UTC, aravindvnair99 requested changes
@suneel87 Don't replace symbols with HTML entities for comments.

2020-10-10 09:34 UTC, aravindvnair99 approved these changes

2020-10-10 09:34 UTC, merged