combining Fest and About page
aravindvnair99/AYKYA-Fest pull request #37
Opened 2020-10-01 06:12 UTC by Subaharish

Signed-off-by: Subaharish <48942935+Subaharish@users.noreply.github.com>

2020-10-03 14:24 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is there

2020-10-03 14:24 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is there

2020-10-03 14:24 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
Label tag is there

2020-10-03 14:24 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is there

2020-10-03 14:25 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is there

2020-10-03 14:27 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
only one label tag is there

2020-10-03 14:27 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
Label tag is there

2020-10-03 14:29 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
only one label tag is there

2020-10-03 14:29 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
Label tag is there

2020-10-03 14:29 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is there

2020-10-03 14:29 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is there

2020-10-03 14:30 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
Label tag is there

2020-10-03 14:30 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
Label tag is there

2020-10-03 14:30 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
only one label tag is there

2020-10-03 14:30 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_4">
Label tag is there

2020-10-05 05:53 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn">
Label tag is present

2020-10-05 05:53 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-05 05:53 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is present

2020-10-05 05:54 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-05 05:54 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is present

2020-10-05 05:54 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-05 05:54 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is present

2020-10-05 05:54 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-05 05:55 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn">
Label tag is present

2020-10-05 05:55 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is present

2020-10-05 05:55 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-05 07:33 UTC, VinayakTekade requested changes
@Subaharish Change the layout of images and along with the text so that images are clearer.

2020-10-05 12:23 UTC, Subaharish commented
> @Subaharish Change the layout of images and along with the text so that images are clearer. Don't worry about CodeFactor issues. I will fix it.

@VinayakTekade Resized the images and Changed the font color

2020-10-07 03:21 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
label tag is present

2020-10-07 03:22 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
label tag is present

2020-10-07 03:22 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
label tag is present

2020-10-07 03:38 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is present

2020-10-07 03:38 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_2">
Label tag is present

2020-10-07 03:38 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-07 03:38 UTC, Subaharish commented on functions/views/about.ejs
> +										<input type="checkbox" name="button" id="collapse-btn_3">
Label tag is present

2020-10-11 17:11 UTC, merged